import { Geist, Geist_Mono, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlexSerif = IBM_Plex_Serif({
  subsets: ["latin"],
  weight: ["400", "700"], // Adjust weights as needed
  variable: "--font-ibm-plex-serif" // Custom CSS variable
});

export const metadata = {
  title: "Sangita - Corporate Trainer",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Head>
      {/* Standard Favicon */}
      <link rel="icon" type="image/x-icon" href="/favicon.ico" />

      {/* PNG Favicons */}
      <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />


      {/* Apple Touch Icon */}
      <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />

      {/* Android Chrome Icon */}
      <link rel="icon" type="image/png" sizes="192x192" href="/favicon-192x192.png" />

      {/* Manifest (Optional for PWA) */}
      <link rel="manifest" href="/site.webmanifest" />
    </Head>
      <body className={`${geistSans.variable} ${geistMono.variable} ${ibmPlexSerif.variable}`}>
        {children}
      </body>
    </html>
  );
}
